/**
 * PWA Service
 * Generates manifest.json, service worker, and icons
 */

export function generateManifest({ name, shortName, description, themeColor = '#6366f1' }) {
  return {
    name,
    short_name: shortName || name.slice(0, 12),
    description: description || 'PWA App',
    start_url: '/',
    display: 'standalone',
    background_color: '#0d0d0d',
    theme_color: themeColor,
    orientation: 'portrait-primary',
    icons: [
      {
        src: '/icon-192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any maskable'
      },
      {
        src: '/icon-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any maskable'
      }
    ],
    categories: ['utilities'],
    lang: 'ko'
  };
}

export function generateServiceWorker({ cacheName }) {
  return `const CACHE_NAME = '${cacheName}';
const OFFLINE_URL = '/offline.html';

// Install event - cache core assets
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll([
        '/',
        '/index.html',
        '/manifest.json',
        OFFLINE_URL
      ]);
    })
  );
  self.skipWaiting();
});

// Activate event - clean old caches
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames
          .filter((name) => name !== CACHE_NAME)
          .map((name) => caches.delete(name))
      );
    })
  );
  self.clients.claim();
});

// Fetch event - network first, fallback to cache
self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  
  event.respondWith(
    fetch(event.request)
      .then((response) => {
        // Cache successful responses
        const responseClone = response.clone();
        caches.open(CACHE_NAME).then((cache) => {
          cache.put(event.request, responseClone);
        });
        return response;
      })
      .catch(() => {
        // Network failed, try cache
        return caches.match(event.request).then((cachedResponse) => {
          return cachedResponse || caches.match(OFFLINE_URL);
        });
      })
  );
});

// Push notification support (placeholder)
self.addEventListener('push', (event) => {
  const data = event.data?.json() ?? {};
  const title = data.title || '앱 알림';
  const options = {
    body: data.body || '새로운 알림이 있습니다',
    icon: '/icon-192.png',
    badge: '/icon-192.png'
  };
  event.waitUntil(
    self.registration.showNotification(title, options)
  );
});
`;
}

export function generateOfflinePage() {
  return `<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>오프라인</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, sans-serif;
      background: #0d0d0d;
      color: #fff;
      display: flex;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      text-align: center;
      padding: 20px;
    }
    .offline-icon { font-size: 48px; margin-bottom: 16px; }
    h1 { margin-bottom: 8px; }
    p { color: #a0a0a0; }
  </style>
</head>
<body>
  <div>
    <div class="offline-icon">📡</div>
    <h1>오프라인 상태</h1>
    <p>인터넷 연결을 확인해주세요.</p>
  </div>
</body>
</html>`;
}

export function addPWASupport(files, projectName) {
  const safeName = projectName.replace(/[^a-z0-9]/g, '-').slice(0, 20);
  
  // Add or update manifest.json
  const manifestContent = JSON.stringify(generateManifest({
    name: projectName,
    shortName: safeName,
    description: `Generated by 딸깍 배포`
  }), null, 2);
  
  // Add service worker
  const swContent = generateServiceWorker({
    cacheName: `${safeName}-v1`
  });
  
  // Add offline page
  const offlineContent = generateOfflinePage();
  
  return [
    ...files.filter(f => !['manifest.json', 'sw.js', 'offline.html'].includes(f.path)),
    { path: 'manifest.json', content: manifestContent },
    { path: 'sw.js', content: swContent },
    { path: 'offline.html', content: offlineContent }
  ];
}
